#!/usr/bin/env bash#/bin/bash
# Utility for checking files all converted files from source directory are in destination
SAVEIFS=$IFS
IFS=$(echo -en "\n\b")
folder1=$1 #"/Volumes/expansion/project/data/src/training"
folder2=$2 #"/Volumes/expansion/project/data/dst/training"
ext1=$3 #"mp3"
ext2=$4 #"wav"


for fullfile in ${folder1}/*.$ext1
do
        #echo "$fullfile fullfile"
        filename=$(basename "$fullfile")
        #echo "$filename file"
        extension="${filename##*.}"
        #echo "$extension ext"
        cleanfilename="${filename%.*}"
        #echo "$cleanfilename base"
        if ! [ -a "${folder2}/$cleanfilename.$ext2" ]
        then
                echo $fullfile
        fi
done
IFS=$SAVEIFS