training_src_path = "/Volumes/expansion/project/data/src/training/"
training_dst_path = "/Volumes/expansion/project/data/dest/training/"
test_src_path = "/Volumes/expansion/project/data/src/test/"
test_dst_path = "/Volumes/expansion/project/data/dest/test/"
dst_ext = ".wav"